services:
  # MySQL 데이터베이스 설정
  mysql-database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # MySQL root 비밀번호 설정
      MYSQL_DATABASE: test  # 초기 데이터베이스 이름
      MYSQL_USER: root   # 애플리케이션 사용자
      MYSQL_PASSWORD: 1234  # 애플리케이션 사용자 비밀번호
    ports:
      - "3306:3306"  # MySQL 기본 포트

  # MongoDB 설정
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  # MongoDB 기본 포트

  # Redis 설정
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"  # Redis 기본 포트
    environment:
      PASSWORD: 1234

  # Spring Boot 애플리케이션
  app:
    build:
      context: .  # Dockerfile이 있는 디렉토리
      dockerfile: /Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"  # Spring Boot 애플리케이션 포트
    environment:
      SPRING_DATASOURCE_URL : jdbc:mysql://mysql-database:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATA_MONGODB_URI : mongodb://mongodb:27017/study
      SPRING_REDIS_HOST : redis
      JWT_SECRET_KEY : adsadasdsaiocvkcvcxovcx90uewqwd3dcxjvcxcoiuvxcoivuxcdwasoodusaczx  # 환경 변수로 JWT 비밀 키 전달
    depends_on:
      - h2
      - mongodb
      - redis
